server:
  port: 10003

spring:
  application:
    name: study-zuul

eureka:
  client:
    service-url:
      defaultZone: http://localhost:10001/eureka/  # 服务中心地址

zuul:
  routes:
    study-system:
      path: /system/**
      serviceId: study-system
